### ISSUE TITLE
Design Hero Section

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/website-screens#10]
### Description

Follow the contribution guidelines and code of conduct

Design a responsive Hero Section for websites.
Refer to [some existing design](https://github.com/Dezenix/website-screens/blob/main/Website_Hero_Section/Hero04/README.md) and bring some innovative Idea

**Comment by suyogkokaje** [comment]
Hello @GovindSingh9447 I would like to make a responsive Hero section for a website. Could you please assign this issue to me?

**Comment by GovindSingh9447** [comment]
Sure, But you have to submit it within 2 days. Otherwise I will assign this issues to someone else.
@suyogkokaje  Are you participant's of WoC/SWoC??

**Comment by suyogkokaje** [comment]
Yes, I will complete it within two days. I am SWoC participant. Also I want to ask one question. I have to replicate exact same thing in the figma file or can I create Hero section of my own ?

**Comment by GovindSingh9447** [comment]
You have to make your own.
