### ISSUE TITLE
Design Real Estate Landing Page

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/website-screens#17]
### Description

Follow the contribution guidelines and code of conduct
Design Real estate Landing Page.

**Comment by Gaurav4code** [comment]
Please assign me this issue.

**Comment by suyogkokaje** [comment]
Hello @GovindSingh9447 I would like to work on this landing page. Could you please assign this issue to me? I am SWoC contributor
(Its a request, because the another issue is of portfolio website and I have already contributed one (PR 13). I want to work on this landing page)

**Comment by GovindSingh9447** [comment]
> Please assign me this issue.

@Gaurav4code , I can't assign 2 issues to same person at a same time. First complete the [Portfolio website](https://github.com/Dezenix/website-screens/issues/19) then I will assign you other one.

**Comment by GovindSingh9447** [comment]
> Hello @GovindSingh9447 I would like to work on this landing page. Could you please assign this issue to me? I am SWoC contributor (Its a request, because the another issue is of portfolio website and I have already contributed one (PR 13). I want to work on this landing page)

Of course @suyogkokaje, you can work on it.

**Comment by suyogkokaje** [comment]
Thank you so much.
