### ISSUE TITLE
Time Tracking 

### ISSUE THREAD

**Issue by GovindSingh9447** [Dezenix/website-screens#35]
### Description

Follow the contribution guidelines and code of conduct
Design Time Tracker Dashboard UI:-
[Sample Work](https://youtu.be/co1WyOqqcc0)

**Comment by vishal1patidar** [comment]
I want to work on this issue.

**Comment by GovindSingh9447** [comment]
> I want to work on this issue.

Sure @vishal1patidar

**Comment by vishal1patidar** [comment]
yes

**Comment by mohammadshaad** [comment]
I want to work on this issue I am a contributor in GSSoC'22

**Comment by mohammadshaad** [comment]
The UI of complete website or just the Dashboard page should be designed @GovindSingh9447 ?

**Comment by GovindSingh9447** [comment]
> The UI of complete website or just the Dashboard page should be designed @GovindSingh9447 ?

@mohammadshaad  Complete Website.

**Comment by GovindSingh9447** [comment]
@mohammadshaad are you still working on the issue??
Make PR till tomorrow evening.
