### ISSUE TITLE
Portfolio Website 

### ISSUE THREAD

**Issue by mohammadshaad** [Dezenix/website-screens#39]
### Description

I want to work on Portfolio 2 
Kindly assign me this issue I am a contributor in GSSoC'22

### Additional information

Portfolio 1 is already there

**Comment by Tiya0310** [comment]
Could you describe the issue a little bit, do the contributor have to design the portfolio website or create one?

**Comment by mohammadshaad** [comment]
I guess we have to create and design it

**Comment by mohammadshaad** [comment]
I have made a pull request @GovindSingh9447 
Please check and merge it
