### ISSUE TITLE
Food Delivering Website Landing Page

### ISSUE THREAD

**Issue by mohammadshaad** [Dezenix/website-screens#48]
### Description

I want to design the UI of the food delivering company's website landing page

### Additional information

I am a GSSoC'22 contributor

**Comment by Jaideep25-tech** [comment]
yeah sure you can
@mohammadshaad

**Comment by Jaideep25-tech** [comment]
whats the update

**Comment by mohammadshaad** [comment]
Yeah will make the PR soon @Jaideep25-tech
